# Generated by Django 5.1.7 on 2025-04-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=122)),
                ('user_name', models.CharField(max_length=122)),
                ('area_name', models.CharField(max_length=122)),
                ('village_city', models.CharField(max_length=122)),
                ('policestation', models.CharField(max_length=122)),
                ('district', models.CharField(max_length=122)),
                ('pincode', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('country', models.CharField(max_length=122)),
                ('dob', models.CharField(max_length=122)),
                ('mobile_number', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('photo', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
            ],
        ),
    ]
