# Generated by Django 5.1.7 on 2025-04-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_priamry_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_area', models.CharField(max_length=255)),
                ('user_village_city', models.CharField(max_length=255)),
                ('user_police_station', models.CharField(max_length=255)),
                ('user_district', models.CharField(max_length=255)),
                ('user_pincode', models.CharField(max_length=10)),
                ('user_state', models.CharField(max_length=255)),
                ('user_country', models.CharField(max_length=255)),
                ('user_dob', models.DateField()),
                ('user_mobile_number', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
