# Generated by Django 5.1.7 on 2025-04-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_farmer_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertFarmer',
            fields=[
                ('expert_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience_year', models.IntegerField()),
                ('specialization', models.CharField(max_length=255)),
                ('farm_size', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('crops_grown', models.TextField()),
                ('soil_type', models.CharField(max_length=255)),
                ('irrigation_system', models.CharField(max_length=255)),
                ('fertilizers_used', models.TextField()),
                ('pest_control_methods', models.TextField()),
            ],
        ),
    ]
