# Generated by Django 5.1.7 on 2025-04-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_expertfarmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertfarmer',
            name='location',
        ),
        migrations.AddField(
            model_name='expertfarmer',
            name='certifications',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expertfarmer',
            name='equipments_owned',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expertfarmer',
            name='expert_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expertfarmer',
            name='expert_photo',
            field=models.ImageField(blank=True, null=True, upload_to='expertPhotos/'),
        ),
        migrations.AddField(
            model_name='expertfarmer',
            name='farming_techniques',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expertfarmer',
            name='goverment_subsides',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expertfarmer',
            name='sustainable_practices',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expertfarmer',
            name='technologies_used',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expertfarmer',
            name='weather_adaptibility',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='expertfarmer',
            name='irrigation_system',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='expertfarmer',
            name='soil_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='expertfarmer',
            name='specialization',
            field=models.CharField(default='', max_length=255),
        ),
    ]
