# Generated by Django 5.1.7 on 2025-04-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_expertfarmer_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertfarmer',
            name='experience_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expertfarmer',
            name='expert_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expertfarmer',
            name='fertilizers_used',
            field=models.TextField(blank=True, null=True),
        ),
    ]
