# Generated by Django 5.1.7 on 2025-04-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_expertfarmer_experience_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('expert', 'Expert'), ('admin', 'Admin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_type', models.CharField(max_length=50)),
                ('crop_season', models.CharField(max_length=50)),
                ('crop_growth_duration', models.IntegerField(help_text='Days to maturity')),
                ('crop_description', models.TextField()),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to='cropPhotos/')),
                ('crop_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_type', models.CharField(max_length=50)),
                ('fertilizer_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('application_stage', models.CharField(max_length=100)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_time', models.CharField(max_length=100)),
                ('yield_per_acre', models.FloatField()),
                ('harvesting_method', models.CharField(max_length=100)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('irrigation_schedule', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.crop')),
            ],
        ),
        migrations.CreateModel(
            name='PestDiseaseManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('control_measures', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.crop')),
            ],
        ),
        migrations.CreateModel(
            name='PostHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drying_method', models.CharField(max_length=100)),
                ('storage_condition', models.TextField()),
                ('packaging_method', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.crop')),
            ],
        ),
        migrations.CreateModel(
            name='SeedDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_variety', models.CharField(max_length=100)),
                ('seed_rate_per_acre', models.FloatField()),
                ('seed_source', models.CharField(blank=True, max_length=200)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.crop')),
            ],
        ),
        migrations.CreateModel(
            name='SoilRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=100)),
                ('soil_pH_range', models.CharField(max_length=50)),
                ('nutrients_needed', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.crop')),
            ],
        ),
        migrations.CreateModel(
            name='SowingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowing_method', models.CharField(max_length=100)),
                ('spacing', models.CharField(max_length=50)),
                ('sowing_depth', models.FloatField()),
                ('sowing_time', models.CharField(max_length=100)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.crop')),
            ],
        ),
        migrations.CreateModel(
            name='WeedControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('timing', models.CharField(max_length=100)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.crop')),
            ],
        ),
    ]
