# Generated by Django 5.1.7 on 2025-04-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_admin_crop_fertilizer_harvest_irrigation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='irrigation',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='pestdiseasemanagement',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='postharvest',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='seeddetail',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='soilrequirement',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='sowingprocess',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='weedcontrol',
            name='crop',
        ),
        migrations.DeleteModel(
            name='Fertilizer',
        ),
        migrations.DeleteModel(
            name='Harvest',
        ),
        migrations.DeleteModel(
            name='Irrigation',
        ),
        migrations.DeleteModel(
            name='PestDiseaseManagement',
        ),
        migrations.DeleteModel(
            name='PostHarvest',
        ),
        migrations.DeleteModel(
            name='SeedDetail',
        ),
        migrations.DeleteModel(
            name='SoilRequirement',
        ),
        migrations.DeleteModel(
            name='SowingProcess',
        ),
        migrations.DeleteModel(
            name='WeedControl',
        ),
    ]
