# Generated by Django 5.1.7 on 2025-04-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_harvest_crop_remove_irrigation_crop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_created_by',
            field=models.IntegerField(),
        ),
    ]
