# Generated by Django 5.1.7 on 2025-04-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_crop_crop_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
    ]
