# Generated by Django 5.1.7 on 2025-04-10 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_admin_delete_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='systemAdmin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_dob', models.CharField(max_length=100)),
                ('admin_address', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='adminCrop',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=50)),
                ('crop_duration', models.PositiveIntegerField()),
                ('crop_season', models.CharField(max_length=100)),
                ('crop_image', models.ImageField(upload_to='crop_images/')),
                ('crop_description', models.TextField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.systemadmin')),
            ],
        ),
    ]
