# Generated by Django 5.1.7 on 2025-04-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_systemadmin_admincrop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminCrop',
        ),
        migrations.DeleteModel(
            name='systemAdmin',
        ),
    ]
