# Generated by Django 5.1.7 on 2025-04-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_admindisease_adminfertilizer_adminharvesting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsoil',
            name='organic_matter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='adminsoil',
            name='soil_depth',
            field=models.TextField(),
        ),
    ]
