# Generated by Django 5.1.7 on 2025-04-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_adminsoil_organic_matter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminseed',
            old_name='admin_crop',
            new_name='crop_id',
        ),
        migrations.AlterField(
            model_name='expertfarmer',
            name='expert_photo',
            field=models.ImageField(upload_to='expertPhotos/'),
        ),
    ]
