# Generated by Django 5.1.7 on 2025-04-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_admin_crop_adminseed_crop_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='user_photo',
            field=models.ImageField(upload_to='user_photos/'),
        ),
    ]
