# Generated by Django 5.1.7 on 2025-04-19 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_farmer_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='expertVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_file', models.FileField(upload_to='expertVideos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='expertThumbnails/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('views', models.IntegerField(default=0)),
                ('expert_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.expertfarmer')),
            ],
        ),
    ]
