# Generated by Django 5.1.7 on 2025-04-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_expertvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminseed',
            old_name='crop_id',
            new_name='admin_crop',
        ),
        migrations.AlterField(
            model_name='adminsoil',
            name='organic_matter',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='adminsoil',
            name='soil_depth',
            field=models.FloatField(),
        ),
    ]
