# Generated by Django 5.1.7 on 2025-04-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_crop_id_adminseed_admin_crop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='farmer_priamry_id',
            new_name='farmer_primary_id',
        ),
    ]
