# Generated by Django 5.1.7 on 2025-04-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_farmer_priamry_id_farmer_farmer_primary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
