# Generated by Django 5.1.7 on 2025-04-20 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_farmer_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerProject',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('crop_name', models.CharField(max_length=255)),
                ('crop_type', models.CharField(max_length=255)),
                ('farm_size', models.CharField(max_length=255)),
                ('farm_location', models.CharField(max_length=255)),
                ('farm_address', models.CharField(max_length=10)),
                ('soil_name', models.CharField(max_length=255)),
                ('current_session', models.CharField(max_length=255)),
                ('starting_date', models.DateField()),
                ('complete', models.BooleanField()),
                ('description', models.TextField()),
                ('project_photo', models.ImageField(upload_to='userProjectPhotos/')),
                ('farmer_primary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.farmer')),
            ],
        ),
    ]
