# Generated by Django 5.1.7 on 2025-04-24 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_farmerconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerQuery',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_title', models.CharField(max_length=200)),
                ('query_text', models.TextField()),
                ('query_image', models.ImageField(blank=True, null=True, upload_to='query_images/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('solution_text', models.TextField(blank=True, null=True)),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to='solution_images/')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.expertfarmer')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.farmer')),
            ],
        ),
    ]
