# Generated by Django 5.1.7 on 2025-05-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_farmersoil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farmerSoil',
        ),
    ]
