# Generated by Django 5.1.7 on 2025-05-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_delete_farmersoil'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerSoil',
            fields=[
                ('farmer_soil_id', models.AutoField(primary_key=True, serialize=False)),
                ('soil_type', models.CharField(max_length=100)),
                ('ph_level', models.FloatField(blank=True, null=True)),
                ('nitrogen', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('organic_matter', models.FloatField(blank=True, null=True)),
                ('amendments', models.TextField(blank=True)),
                ('tools_used', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ml_prediction', models.CharField(blank=True, max_length=200)),
                ('ml_confidence', models.FloatField(blank=True, help_text='Confidence score from 0 to 1', null=True)),
                ('soil_image', models.ImageField(blank=True, upload_to='farmer_soils/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.farmerproject')),
            ],
        ),
    ]
