# Generated by Django 5.1.7 on 2025-05-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_farmersoil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmersoil',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='farmersoil',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
