# Generated by Django 5.1.7 on 2025-05-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_farmersoil_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farmerSoil',
        ),
    ]
