# Generated by Django 5.1.7 on 2025-05-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_farmersoil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmersoil',
            old_name='project_id',
            new_name='project',
        ),
    ]
