# Generated by Django 5.1.7 on 2025-05-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_farmersowing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farmerSowing',
        ),
    ]
