# Generated by Django 5.1.7 on 2025-05-07 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_delete_farmersowing'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerSowing',
            fields=[
                ('farmer_sowing_id', models.AutoField(primary_key=True, serialize=False)),
                ('seed_variety', models.CharField(max_length=100)),
                ('seed_treatment', models.TextField(blank=True)),
                ('sowing_time', models.CharField(max_length=100)),
                ('seed_rate', models.FloatField(help_text='kg/acre')),
                ('sowing_method', models.CharField(max_length=100)),
                ('row_spacing', models.CharField(max_length=50)),
                ('sowing_depth', models.CharField(max_length=50)),
                ('equipment_used', models.TextField(blank=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('ml_prediction', models.CharField(blank=True, max_length=200)),
                ('ml_confidence', models.FloatField(blank=True, help_text='Confidence score from 0 to 1', null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('sowing_image', models.ImageField(blank=True, upload_to='farmer_sowings/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.farmerproject')),
            ],
        ),
    ]
