# Generated by Django 5.1.7 on 2025-05-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_farmerdisease_farmerfertilizer_farmergrowthstage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersoil',
            name='expert_advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
