# Generated by Django 5.1.7 on 2025-05-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_farmersoil_expert_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdisease',
            name='expert_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerfertilizer',
            name='expert_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmergrowthstage',
            name='expert_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerharvesting',
            name='expert_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerirrigation',
            name='expert_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerothers',
            name='expert_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerpest',
            name='expert_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerpostharvesting',
            name='expert_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmersowing',
            name='expert_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerweed',
            name='expert_advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
