# Generated by Django 5.1.7 on 2025-05-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_farmerdisease_expert_advice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmersoil',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmersoil',
            name='temparature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
