# Generated by Django 5.1.7 on 2025-05-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_farmerdisease_cause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincrop',
            name='crop_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmersowing',
            name='row_spacing',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmersowing',
            name='sowing_depth',
            field=models.CharField(max_length=255),
        ),
    ]
