# Generated by Django 5.1.7 on 2025-05-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_admincrop_crop_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerdisease',
            old_name='expert_advice',
            new_name='expert_advise',
        ),
        migrations.RenameField(
            model_name='farmerfertilizer',
            old_name='expert_advice',
            new_name='expert_advise',
        ),
        migrations.RenameField(
            model_name='farmergrowthstage',
            old_name='expert_advice',
            new_name='expert_advise',
        ),
        migrations.RenameField(
            model_name='farmerharvesting',
            old_name='expert_advice',
            new_name='expert_advise',
        ),
        migrations.RenameField(
            model_name='farmerirrigation',
            old_name='expert_advice',
            new_name='expert_advise',
        ),
        migrations.RenameField(
            model_name='farmerothers',
            old_name='expert_advice',
            new_name='expert_advise',
        ),
        migrations.RenameField(
            model_name='farmerpest',
            old_name='expert_advice',
            new_name='expert_advise',
        ),
        migrations.RenameField(
            model_name='farmerpostharvesting',
            old_name='expert_advice',
            new_name='expert_advise',
        ),
        migrations.RenameField(
            model_name='farmersoil',
            old_name='expert_advice',
            new_name='expert_advise',
        ),
        migrations.RenameField(
            model_name='farmersowing',
            old_name='expert_advice',
            new_name='expert_advise',
        ),
        migrations.RenameField(
            model_name='farmerweed',
            old_name='expert_advice',
            new_name='expert_advise',
        ),
    ]
