# Generated by Django 5.1.7 on 2025-05-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_rename_expert_advice_farmerdisease_expert_advise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminharvesting',
            old_name='cropId',
            new_name='crop_id',
        ),
    ]
